"""add users_confirmed

Revision ID: 326c7e85af25
Revises: be047b7c0d2a
Create Date: 2023-05-14 18:11:34.552399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326c7e85af25'
down_revision = 'be047b7c0d2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
