"""Init

Revision ID: 395c13a0a2bd
Revises: ad5610372f62
Create Date: 2023-05-01 20:31:24.356217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395c13a0a2bd'
down_revision = 'ad5610372f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
