"""Init

Revision ID: ad5610372f62
Revises: 5204bcdf2249
Create Date: 2023-05-01 13:37:23.901152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5610372f62'
down_revision = '5204bcdf2249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    # ### end Alembic commands ###
